# Generated by Django 3.2.2 on 2021-10-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song_comment',
            old_name='post_id',
            new_name='blog_id',
        ),
    ]
