# Generated by Django 3.2.8 on 2021-10-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_rename_post_id_song_comment_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
