# Generated by Django 3.2.8 on 2021-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_s_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
