# Generated by Django 3.2.8 on 2021-10-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song_bookmark',
        ),
    ]
