# Generated by Django 3.2.8 on 2021-10-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_delete_song_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='s_blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='song.Song_hashtag'),
        ),
    ]
