# Generated by Django 3.2.3 on 2021-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gram',
            name='writer',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
