# Generated by Django 3.2.3 on 2021-10-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kim', '0002_alter_gram_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gram_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kim.gram')),
            ],
        ),
    ]
