# Generated by Django 3.2.3 on 2021-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kim', '0003_gram_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gram',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
